### ISSUE TITLE
SNOW-161954: Temporary Directory Path Not Windows-Compatible 

### ISSUE THREAD

**Issue by rtimothyweeks** [snowflakedb/snowflake-connector-python#310]
The path to the parquet chunks has a hard-coded, Unix-style slash. Better to use something like pathlib, rather than format to construct the path to the files?

https://github.com/snowflakedb/snowflake-connector-python/blob/be43eebae138b0040fb973ba470b7575bae97a0f/pandas_tools.py#L103

**Comment by sfc-gh-mkeller** [comment]
Did this fail for you? It seems to have passed testing for us.
Although, I should fix this, thanks for reporting it!

**Comment by rtimothyweeks** [comment]
Yes, using the write_pandas function on a simple dataframe returns a batch of SQL errors. I believe all of the syntax errors are due to the format of the temp directory path on Windows.

ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 87 unexpected '~'.
parse error line 1 at position 94 near '65'.
parse error line 1 at position 102 near '76'.
parse error line 1 at position 108 near '84'.
parse error line 1 at position 113 near '116'.
syntax error line 1 at position 124 unexpected '/'.
syntax error line 1 at position 130 unexpected '.'.
syntax error line 1 at position 135 unexpected '@"tjieh"'.

**Comment by sfc-gh-mkeller** [comment]
I'll get this fixed and merged as soon as possible. This is a really simple fix.
Look for the fix in the next release and please close this ticket when you verified that the issue has been fixed.

**Comment by rtimothyweeks** [comment]
@sfc-gh-mkeller I just reran with snowflake-connector-python==2.2.7, and the "syntax error line 1 at position 124 unexpected '/'." is fixed, but all the other parse and syntax errors still remain. Do you want me to close this ticket?

**Comment by sfc-gh-mkeller** [comment]
Please, let me know of all syntax and parse errors.

**Comment by rtimothyweeks** [comment]
Here are all of the errors- You can see that the unexpected '/' error is gone, but the COPY INTO query is still not formatting correctly.

ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 1 at position 87 unexpected '~'.
parse error line 1 at position 98 near '76'.
parse error line 1 at position 104 near '84'.
parse error line 1 at position 109 near '116'.
parse error line 1 at position 121 near '102'.
syntax error line 1 at position 126 unexpected '.'.
syntax error line 1 at position 131 unexpected '@"guukg"'.

**Comment by sfc-gh-mkeller** [comment]
Okay, let me dust off my Windows VM to try doing this as I'd need to see the SQL query to see the issue.

**Comment by sfc-gh-mkeller** [comment]
@rtimothyweeks I'm sorry I'm unable to reproduce this still locally.
Could you please post the "COPY INTO" command that write_pandas is trying to run?
Here's what mine looks like:
```
'COPY INTO "driver_versions" /* Python:snowflake.connector.pandas_tools.write_pandas() */ FROM @"dmxxa" FILE_FORMAT=(TYPE=PARQUET COMPRESSION=auto) MATCH_BY_COLUMN_NAME=CASE_SENSITIVE  PURGE=TRUE ON_ERROR=abort_statement'
```
However in our new CI this gets reproduced: https://github.com/snowflakedb/snowflake-connector-python/runs/824563046?check_suite_focus=true

**Comment by sfc-gh-mkeller** [comment]
Nevermind, I found the issue
https://github.com/snowflakedb/snowflake-connector-python/commit/fa7d80d4bedaa2ab933683576719c2d1bdd2ddcf fixes it.
